### ISSUE TITLE
Timers not showing

### ISSUE THREAD

**Issue by Bolaski** [MOUZU/TotemTimers-Enhanced#1]
Hey there, I have the timer on the icon appearing but the timer under the timer shows at ... I've tried downloading the latest version and turning off all my addons and deleting my font folder. Can you guys please help me with a fix? i really love this addon but I can't get it to function. :(

**Comment by MOUZU** [comment]
Hello there, I'm not sure if I find time to look into this but it sounds like the issue is rather related to your UIScale settings and not the AddOn itself.

**Comment by MOUZU** [comment]
closing this old issue, as I've mentioned in my previous comment - any issue with text disappearing and instead displaying "..." is related to a UIScale issue and therefore not related to a specific AddOn.
