### ISSUE TITLE
Improved fire totem Talent 

### ISSUE THREAD

**Issue by Maroej** [MOUZU/TotemTimers-Enhanced#3]
Improved fire totem Talent (reducing the explosion from 3 sec to 1) bugs out the addon. 

My suspicion is that this bug also disables you from /lunamo on yourself with any healing spell (in LUNA player frame and in raid frame, guess in party frames too but who uses that anyway). 

Wierd thing is even after deleting the totemtimers saved variables it is still the same.

Will try to recreate the bug so I can take a SS as I haven't thought much of it when it happened so I didn't record it. I assumed that you didn't change that as it is not really of consequence but atm I can't use totemtimers Enhanced because of this reason

**Comment by Maroej** [comment]
still have the same issue with the lunamo on my own frame and my frame in luna raid frames even with the "new" (update 25 days ago) fix and a clean WTF folder

**Comment by Maroej** [comment]
Any solution to this ? I started using alt for selfcast exclusively to heal myself but I would still like lunamo to work on my own frame.

**Comment by MOUZU** [comment]
I'll try to get some time in the next weeks to take a look at your issues.

**Comment by MOUZU** [comment]
I couldn't reproduce the issue. I would need the exact error message and preferably a screenshot or a description of the situation to investigate further
