### ISSUE TITLE
Timers not following the totem display order change

### ISSUE THREAD

**Issue by Maroej** [MOUZU/TotemTimers-Enhanced#4]
Timers not following the totem display order change. If you switch the totem order it will still show the timer in the place the totem was originally. For example if you change earth and water totem place order and cast tremor it will still show tremor timer all the way on the right where earth is usually placed. Not really important honestly but can confuse some people

**Comment by MOUZU** [comment]
I could reproduce the issue. If the Totem order changed from the default settings, the bug appears on summoning a totem. It will lead to the fact that the first animation is placed on the slot where the totem would be in the default order.

I'm looking for a solution.

**Comment by MOUZU** [comment]
This was a pain in the ass to debug. Apparently the TotemTimer Frames are numbered in reverse order to the actual "Order" which is being configured by the user. (Element nr 1. in the Order is being displayed in Frame nr. 4 ...)
